# Generated by Django 4.1.4 on 2023-07-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
